### ISSUE TITLE
October Meeting and Agenda

### ISSUE THREAD

**Issue by Westbrook** [w3c/webcomponents-cg#101]
For those of you who would like to take part in the October meeting of the Web Components Community Group, please share your availability [here](https://www.when2meet.com/?26766850-cQWs1) as we work to schedule the right day/time to gather. Don't forget, all WCCG events are listed on [this calendar](https://calendar.google.com/calendar/u/0/embed?src=o25bim5rvcu42mfnqilirpmp44@group.calendar.google.com). 📆

As a reminder, we chat between meetings in Discord, where [we'd love to hear from you](https://discord.gg/SusMutmw).

If there are other topics you'd like to discuss, breakouts you would already like to have scheduled, or anything else, please drop your thoughts in the comments below!

**Comment by Westbrook** [comment]
Some, none, or all of these topics may be of interest:
- TPAC notes
  - Share your recollections to https://docs.google.com/document/d/1InarfFG8L9P7a444UXTx_z3Euyx2M3Vq-80LLA-wXv0/edit
- Interop 2025
  - https://webkit.org/blog/15942/get-ready-for-interop-2025-your-chance-to-shape-the-web/
- WCCG focus areas 2025
  - What should the 2025 version of https://w3c.github.io/webcomponents-cg/2023.html look like?
  - Should we make a 2024 version, posthumously? 
- Community Protocols, proposals and progressions
  - https://github.com/webcomponents-cg/community-protocols/
- External facing things...
  - broader participation
  - docs/cg/catalog site?

**Comment by michaelwarren1106** [comment]
I'm going to try to work on updating the process idea GH issue today and see if I cant get that in a state where we can review it a second time before talking about adoption and getting some stuff stood up to help on the process side. I've had a lot going on and havent gotten a chance to fold in feedback from the initial review. gonna try to get to it!

**Comment by o-t-w** [comment]
Would it be worth talking about CSS module scripts, seeing as there has been some movement on that recently?

**Comment by Westbrook** [comment]
[Today's notes](https://docs.google.com/document/d/1jOz2Mu8y49j81WPE7__sHkyoUQey6X09JNiYmEh4b1I/edit?tab=t.0#heading=h.8rjjl9b7j61s), as best I can do while leading all the valuable conversation today.

**Action Items**
- [ ] @Westbrook to send around availability like to schedule our next session for 2-3 weeks out

<details>
    <summary>Meeting chat within...</summary>

Alan W. Smith
11:13 AM
I lost audio. brb
Dave Rupert
11:13 AM
So.. uh... did anything interesting happen recently?
You
11:13 AM
https://docs.google.com/document/d/1jOz2Mu8y49j81WPE7__sHkyoUQey6X09JNiYmEh4b1I/edit?tab=t.0
keep
Pinned
You
11:17 AM
https://github.com/w3c/webcomponents-cg/issues/102
https://github.com/w3c/webcomponents-cg/issues/99
Gray Norton
11:24 AM
Makes sense! I do think a concise statement of what specific problems the process is trying to solve, or the goals the process is aiming to achieve, would make the doc stronger, so I'll leave a comment to that effect on the issue!
Owen Buckley
11:28 AM
or if you have any thoughts on this
https://github.com/w3c/webcomponents-cg/issues/100
Owen Buckley
11:31 AM
maybe just a recap from TPAC?
Pascal Vos
11:43 AM
hey michael
Justin Fagnani
11:45 AM
There are two features here:
- inline CSS modules: not tied to shadow DOM
- Referring to a CSS module by URL from a shadow root: yes, tied to shadow DOM
The first feature could be later used from other places if there are any
You can polyfill @sheet with @supports too
Justin Fagnani
11:47 AM
The main innovation here is inlining part of the module graph
and there's *huge* potential there outside of CSS, IMO
Jeroen Zwartepoorte
11:54 AM
I just created this issue; that's my main concern/question with the style sharing proposal. https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/896
Steve Orvell
11:54 AM
FW can see WC as a threat to their existence. This is just an adversarial perspective that doesn't need to exist.
Steve Orvell
11:57 AM
Let's try to be quick in the comments to get a change for everyone to talk in our limited time...
Michael Warren
11:57 AM
sorry, this is a big topic ha
You
11:57 AM
FYI, if you have time, I have time to go through till the Goole Meet hour kicks us off...
Michael Warren
11:59 AM
"the tax" is definitely worse the more you try to abstract away from things. but there are definitely folks that think that the spec is wholly bad and only userland build steps can fix it etc
Gray Norton
11:59 AM
Yeah, but you can recognize that tendency and try to overcome it, or lean into it, and Rich is 100% leaning into it
Dave Rupert
12:00 PM
I think this whole thing exposes some rough edges. We can smooth those edges out. e.g. Everyone's first test drive of Shadow DOM sort of sucks, how do we improve that onboarding.
Joeri Sebrechts
12:00 PM
FWIW, i learned a ton from ryan's livestream, made a 500 line markdown document with notes. There was a lot in there to learn from and respond to.
Steve Orvell
12:00 PM
Ryan's post was really disappointing as well. "biggest threat to the web" isn't a great way to open a discussion
Pascal Vos
12:01 PM
it's not constructive
Nolan Lawson
12:01 PM
it's an exaggeration. people talk differently to their audience than to each other. notice how constructive Ryan was in the Discord
Michael Warren
12:02 PM
I talked to ryan privately some also, he definitely seems like a good candidate for working with us possibly. I think we're still pretty far apart on ideas, but I think he's maybe amenable to coming to work on it
Alan W. Smith
12:03 PM
I'm very new to web components, something I might be able to offer is the experience of someone at the early stage.
Gray Norton
12:04 PM
Markbage?
Nolan Lawson
12:04 PM
That's not necessarily new, though. Speedometer is browsers trying to make frameworks faster
You
12:05 PM
Using frameworks as an exemplar of usage, rather than an exemplar of best practice.
Dave Rupert
12:07 PM
+1 webcomponents.org is slowly turning into a liability
Alan W. Smith
12:08 PM
newbie perspective: didn't know webcomponents.org existed
never hit it in my searches
Nolan Lawson
12:09 PM
I really like Justin's new custom element schema validator tool. If we could streamline linting WCs then we could have a better centralized "storefront"
Owen Buckley
12:09 PM
just know you're competing with "vibes".  its like saying your genre of music or flavor of ice cream is wrong.  IOW, do we believe WCs are subjective, or objective, in they eyes of the beholder?
Nolan Lawson
Nolan Lawson
12:09 PM
Might need some equivalent of definitely-typed though for abandoned WCs
Gray Norton
12:09 PM
I do think rebooting WC.org would be a good thing for this group to consider. The Lit team was trying to move this ball forward, but that didn't pan out
Owen Buckley
12:10 PM
but building and listening is probably a good strategy
Michael Warren
12:10 PM
honestly, if we could track down and write down some of the rationale for how things ended up being built the way they were, that might go a long way...
a lot of folks think "things are weird" but have no context for why they ended up the way they did etc
Alan W. Smith
12:11 PM
is that content outline avaible?
You
12:12 PM
Where might not matter _that_ much in the end.
Michael Warren
12:12 PM
imo highlighting the non-FMAANG contributors to WCs would be huge!
Dave Rupert
12:12 PM
I have a giant list of components, libraries, design systems, metaframeworks, etc. in a Notion. Happy to share/donate that.
Michael Warren
12:12 PM
lots of folks think that WCs are only being driven by the big tech companies and thats increasingly not true
Justin Fagnani
12:13 PM
+1 And can you run those through the validator? :)
https://validator.elematic.dev/
Michael Warren
12:13 PM
https://github.com/w3c/webcomponents-cg/issues/99
Pascal Vos
12:13 PM
thank you for leading again @westbrook
Michael Warren
12:14 PM
does that mean more work on CEM analyzer tools too then? :)
Alan W. Smith
12:14 PM
newbie perspective: I have no idea what a manifest is (eek)
You
12:14 PM
@alan: https://custom-elements-manifest.open-wc.org/
Michael Warren
12:15 PM
https://github.com/webcomponents/custom-elements-manifest
ill try! :)
Alan W. Smith
12:15 PM
have a good one!

</details>
