### ISSUE TITLE
November Scheduling and Agenda

### ISSUE THREAD

**Issue by Westbrook** [w3c/webcomponents-cg#103]
Lots of great talk towards 2025 plays for the WCCG in our October meeting this last week! Let's keep up the momentum and get our November meeting on the calendar. Please share you availability [here](https://www.when2meet.com/?27147878-rGfgl). 🆓 

Don't forget, all WCCG events are listed on [this calendar](https://calendar.google.com/calendar/u/0/embed?src=o25bim5rvcu42mfnqilirpmp44@group.calendar.google.com). 📆

As a reminder, we chat between meetings in Discord, where [we'd love to hear from you](https://discord.gg/kbba8cKPg9). 🗣️ 

If there are other topics you'd like to discuss, breakouts you would already like to have scheduled, or anything else, please drop your thoughts in the comments below! 🙇🏼‍♂️

**Comment by nolanlawson** [comment]
I'd like to discuss Scoped Custom Element Registries, and particularly recent discussions around how to make the API work for libraries/frameworks without having to change how they use the DOM: https://github.com/WICG/webcomponents/issues/1043

**Comment by filimon-danopoulos** [comment]
@michaelwarren1106 should we talk about docs too?

**Comment by Westbrook** [comment]
Notes from this meeting are available [here](https://docs.google.com/document/d/1jOz2Mu8y49j81WPE7__sHkyoUQey6X09JNiYmEh4b1I/edit?tab=t.0#heading=h.eot5ldqnv6xh).

# Action Items
- [ ] if you are using some form of registry scoping today and are able to experiment with the Chrome prototype or the coming WebKit implementation to compare it to your current solution, please reach out to us! 🙇🏼‍♂️ 
- [ ] @keithamus will be doing a session on Scoped Registries (either a FireFox implementation or a spec writing session) be on the lookout for timing
- [ ] Let's schedule some breakouts, specifically (for now) on `:has-slotted`, but more, too
- [ ] @Westbrook to share out a when2meet for the December meeting, my availability for this is flipped, so if schedule prevents attendance, I'm happy to share chairperson duty with someone else for the month.

Thanks, everyone! See you next time 👋🏼 

<details>
  <summary>Meeting chat within...</summary>

You
2:02 PM
https://docs.google.com/document/d/1jOz2Mu8y49j81WPE7__sHkyoUQey6X09JNiYmEh4b1I/edit?tab=t.0#heading=h.eot5ldqnv6xh
keep
Pinned
Michael Warren
2:03 PM
im trying to be in two meetings at once for a minute haha
Pascal Vos
2:03 PM
wonderfull day everyone :)
Gray Norton
2:21 PM
FWIW, I had a very nice conversation with Ryan Carniato last week, trying to lay the groundwork for a long-term detente
Justin Fagnani
2:21 PM
+100
Gray Norton
2:21 PM
Will see whether that can be built upon
You
2:21 PM
He's also been somewhat active on the channel, so it's great to hear that something good is coming out of the whole process. Thanks Gray!!
Pascal Vos
2:28 PM
add some things under the subtle or other name to help with intergration could be an option
Dave Rupert
2:32 PM
is there a link to catch up on the shadow realm discussion?
Nolan Lawson
2:33 PM
that's what we're doing
Gray Norton
2:35 PM
Gotta run to another meeting...see y'all in the Discord
Nolan Lawson
2:36 PM
MFE = Micro Front End
Dave Rupert
2:36 PM
We are not using scoped registries, but FAST is setup for it and we could in theory do it with a single env var change. Safari announcing future support puts it on the roadmap but probably far off.
Nolan Lawson
2:39 PM
+1 to status quo
Michael Warren
2:40 PM
unfortunately in a work meeting right now also :(
Dave Rupert
2:42 PM
+1 to overflow meetings. And maybe instead of throwing up optional times, we just say it's the next week at the same time.
Pascal Vos
2:42 PM
i joined keith for a stream on youtube was very wonderfull learning
Steve Orvell
2:45 PM
Specifically, this is really useful imo: https://www.w3.org/TR/design-principles/
Matthew Henry - Q2ADAAAC (he / him)
2:47 PM
oof too soon
Owen Buckley
2:48 PM
you mean kid rock would move to Keith?
You
2:48 PM
+1 for a spec!!!
You
2:51 PM
Reminder that all events are listed in https://calendar.google.com/calendar/u/0/embed?src=o25bim5rvcu42mfnqilirpmp44@group.calendar.google.com
Nolan Lawson
2:51 PM
Some Discords have an #announcements channel
Dave Rupert
2:54 PM
Keith is our avatar!
You
2:55 PM
https://github.com/w3c/csswg-drafts/issues/6867#issuecomment-2395119379
You
3:00 PM
https://github.com/w3ctag/design-reviews/issues/961
Filimon Danopoulos
3:00 PM
Re: Scoping of MFEs. I have attempted a solution of scoping MFEs with iframes before but I did not manage to ship it due complexity and lack of resources to dig further. Do you have any resources to share Nolan?

</details>
