### ISSUE TITLE
[report] Develop the intro to the community report and TPAC session

### ISSUE THREAD

**Issue by justinfagnani** [w3c/webcomponents-cg#25]
Sections we likely need:

* Abstract
* Introduction
* Impact
* Prioritization methodology
* Cross-cutting Themes

For impact we'd like to highlight the large and growing web component usage across the web. Show chromestatus.com number. Any improvements will have a large impact on existing users and open WCs up to new users.

For cross-cutting themes I could see a few areas:
- Re-enable existing HTML/DOM features that are restricted by shadow DOM
- Make WC features work without JS for SSR
- Open up WC usage to more developers - remove walls between WC-style development and global-style development.
- Thoughts on encapsulation: we've had a number of requests to either loosen encapsulation or make it a-la carte. These speak to a number of different potential usages of shadow DOM in particular, starting from what seems to be a base level of having a tree for internal DOM and composition - even without further encapsulation.

**Comment by thescientist13** [comment]
I think our 2021 report touched on this a bit?  We're now in the process of drafting our 2022 report, so not sure if we want to take another iteration on this and make sure we include (label) it as part of 2022 draft?
