### ISSUE TITLE
[navigability] Link to GH Pages from the repo's About section

### ISSUE THREAD

**Issue by hunterloftis** [w3c/webcomponents-cg#28]
We should link to https://w3c.github.io/webcomponents-cg/ from here:

![image](https://user-images.githubusercontent.com/364501/137520958-14259beb-a2e8-453d-9fae-eda1060a9d2e.png)

... and probably also from the README.

**Comment by thescientist13** [comment]
Did we also want to deploy that TPAC 2021 report to a "sub" URL (instead of owning the whole TLD), ex:
https://w3c.github.io/webcomponents-cg/tpac-2021

**Comment by thescientist13** [comment]
Cool, I'll make an issue and see if I can put something together over the next few days.
