### ISSUE TITLE
State of WC survey / focus group

### ISSUE THREAD

**Issue by thescientist13** [w3c/webcomponents-cg#29]
## Overview
As a nod to the corresponding survey's for [JS](https://stateofjs.com/) and [CSS](https://stateofcss.com/) respectively, I wanted to open this issue to start a dialog around the value of having some sort of survey or focus group style effort come out of this group, either in parallel or sequential to, some of the content and branding related efforts being done around WC and webcomponents.org site.

## Motivation
I was mostly inspired from [the work we did to prepare our report](https://docs.google.com/spreadsheets/d/1FUX5Z0Yy-EQB5qIvA04O85c1Ms6YgcWVpUnIeVWVt6M/edit#gid=0), and coming out of our last meeting, thought maybe it would be useful to apply our methods to a larger audience?  This could yield more direct anecdotal experiences from evaluators and consumers of WCs who are specifically _not_ implementors or those of with direct ties to the group that prepared the report in the first place.  Having this kind of information I think would not only be useful to use making tools, docs, etc in the space, but also to surface back up to implementors.

It could also help confirm / deny bias or perceptions that we in this group may have.

I also feel given WC are mostly spec / (developer) use case driven, there can be less of a tooling popularity contest aspect that often times feels like it creeps into surveys like this, which I think is useful for us in the sense that I feel a lot of our work aims to be as objective as possible to ensure that we're trying to focus limited time and resources on the most impactful efforts / pursuits, and thus maximize the payoff to the ecosystem and developer communities as much as possible. 

## Details
To get into a few specific just to help seed the conversation, here are some possible questions or "dialog funnels", as I like to think of them:

- Do you already use Web Components?
- What kind of projects are you building with WC?
- What is your favorite thing about using WCs?
- What is your least favorite thing about using WCs?
- Do you use _only_ WCs for your projects?
- Do you use WCs as part of a design system?
- Are you using any (meta) frameworks to build and / or deliver your WCs?
- Are you using any WC component/ UI libraries or frameworks?
- What would you like to see from WC in the future?
- What would like you like to know more about with WCs?
- What resources help you best when using WCs?
- What resources do you think are missing for WCs?

> As a general theme, I think having questions that are quick to answer, but also allow for an optional "share more information" box, could be a good strategy to get a broad range of responses?  I am by no means a professional survey creator / marketer, just spitballing it all at the moment.  😊 

----

Anyway, that's what I was able to jot down real quick, hope it's a good and useful conversation starter.  Looking forward to thoughts and feedback.  ✌️

**Comment by Westbrook** [comment]
This seems like a smart addition to our overall work!

https://sachagreif.com/ Runs both the CSS and the JS surveys. I wonder if there's anything we could benefit from chatting directly with Sacha here. If there were any way to partner rather than build, that saves us lots of time, etc. etc.  In fact, there may be some preliminary data from the (sometimes lacking) inclusion of WC APIs in the JS survey in the past.

**Comment by alangdm** [comment]
> This seems like a smart addition to our overall work!
> 
> https://sachagreif.com/ Runs both the CSS and the JS surveys. I wonder if there's anything we could benefit from chatting directly with Sacha here. If there were any way to partner rather than build, that saves us lots of time, etc. etc. In fact, there may be some preliminary data from the (sometimes lacking) inclusion of WC APIs in the JS survey in the past.

I second this, it seems they did quite a lot of work to improve the accessibility of the surveys in this year's version so working with Sacha would work well from that side too.

Since I live in the same timezone I could help when contacting Sacha directly if needed

**Comment by Nevraeka** [comment]
These are great questions @thescientist13 . I think it's also important to ask about experience and use cases developers have for each of the major parts of Web Components.  Here are some ideas below...These questions should invoke 1-2 sentence answers and they would be the minority of question types....

1) Have you ever used HTML Template Tags or JavaScript template libraries like LitHTML? If not, how are you handling rendering of your components?

2) Are you using Shadow DOM in your UI components? If so, what are the use case types you have when considering encapsulation in the DOM?

3) What tools do you reach for when creating/using complex form elements in the UI? What are the features and/or reasons you chose these tools?

**Comment by thescientist13** [comment]
Looks like something similar / related is brewing over at https://github.com/web-platform-dx/developer-research/issues/13 ?

**Comment by Westbrook** [comment]
Does https://stateofhtml.com/en-US handle this? Should we look to participate more closely in the 2024 survey?

**Comment by thescientist13** [comment]
Yeah, that would be cool!  I don't think I took it this year, just missed out, but I don't recall anything WC specific in prior years, but I wouldn't take my word for it.  😅

**Comment by Westbrook** [comment]
Feel like this is _generally_ covered by the new State of HTML surveys. Happy to revisit, if you felt it was needed.
