### ISSUE TITLE
[report] Add status details for each browser engine

### ISSUE THREAD

**Issue by justinfagnani** [w3c/webcomponents-cg#36]
Now that both Mozilla and WebKit have standards position repos, and more recent specs have been implemented by multiple browsers, I think it would be useful to expand the **status** section to list each browser engine, like:

**Status**
* Chromium: implemented
* Firefox: position
* WebKit: position

**Comment by thescientist13** [comment]
I think this is covered now by the format @Westbrook shared in Slack and introduced via #37.
