### ISSUE TITLE
2022 Appendix Backlog

### ISSUE THREAD

**Issue by thescientist13** [w3c/webcomponents-cg#44]
Per #43 , just wanted to track all the items in the Appendix we would like to capture for our report in one place, that we can check off as they get added.

> _Discussions for all these are happening in_ #31

1. [x] 🌟 Form-Associated Custom Elements - https://github.com/w3c/webcomponents-cg/pull/42
1. [x] 🌟  Cross-root ARIA - https://github.com/w3c/webcomponents-cg/pull/46
1. [x] 🌟 Constructable Stylesheets & adoptedStyleSheets - https://github.com/w3c/webcomponents-cg/pull/50
1. [x] 🌟 CSS Module Scripts - https://github.com/w3c/webcomponents-cg/pull/58
1. [x] 🌟 Scoped Element Registries - https://github.com/w3c/webcomponents-cg/pull/51
1. [x] 🌟 Declarative Shadow DOM - https://github.com/w3c/webcomponents-cg/pull/45
1. [ ] Composed Selection
1. [ ] Declarative CSS Modules
1. [x] Children changed callback - https://github.com/w3c/webcomponents-cg/pull/40
1. [ ] Open styling of shadow roots
1. [x] Declarative custom elements - https://github.com/w3c/webcomponents-cg/pull/41
1. [x] 🚫 Theming - https://github.com/w3c/webcomponents-cg/pull/54
1. [ ] Styling children of slotted content
1. [x] Custom CSS State - https://github.com/w3c/webcomponents-cg/pull/56
1. [x] 🌟  Imperative Slot Assignment - https://github.com/w3c/webcomponents-cg/pull/55
1. [ ] 🚫 CSS Properties and values inside shadow root 
1. [x] Lazy custom element definitions - https://github.com/w3c/webcomponents-cg/pull/41
1. [x] DOM Parts - https://github.com/w3c/webcomponents-cg/pull/41
1. [x] HTML modules - https://github.com/w3c/webcomponents-cg/pull/60
1. [x] Custom Attributes - https://github.com/w3c/webcomponents-cg/pull/41

----

* 🚫 - has no delegate / owner, or needs help
* 🌟 - featured as part of our #43

**Comment by thescientist13** [comment]
@Westbrook 
Do you have any objections to keeping this issue pinned?  I will also re-open too if that's OK (I will unlink to PRs to GitHub doesn't keep auto closing).

**Comment by Westbrook** [comment]
I just took it off because it said “Closed”. If it’s not closed, let’s put it back. 🙈

**Comment by thescientist13** [comment]
Yeah, I think its a couple years past its time at this point, and not sure if this year is any insight into future precedence as this year we didn't prepare a report.

But the content can certainly be re-used / re-appropriated as need for future reports or other CG efforts!
