### ISSUE TITLE
https://w3c.github.io/webcomponents-cg/ still points to 2021 report

### ISSUE THREAD

**Issue by dandclark** [w3c/webcomponents-cg#63]
The URL https://w3c.github.io/webcomponents-cg/ (listed at https://github.com/w3c/webcomponents-cg as the repo's homepage) still leads to the 2021 report. Should it be updated to point to the latest version at https://w3c.github.io/webcomponents-cg/2022.html?

**Comment by Westbrook** [comment]
We’ll be setting up a landing page so it’s easy to get to both pages, soon.

**Comment by web-padawan** [comment]
Would it be possible to keep the old report at https://w3c.github.io/webcomponents-cg/2021.html for historical reference?

**Comment by Westbrook** [comment]
Yes. I intend to ship an index page, but it keeps falling down the list.

**Comment by thescientist13** [comment]
I opened #65 to add this, just needs some 👀
