### ISSUE TITLE
December Meeting Agenda

### ISSUE THREAD

**Issue by Westbrook** [w3c/webcomponents-cg#76]
For those of you who would like to take part in the December meeting of the Web Components Community Group, please share your availability [here](https://www.when2meet.com/?22281707-A4mbd) as we work to schedule the right day/time to gather. Don't forget, all WCCG events are listed on [this calendar](https://calendar.google.com/calendar/u/0/embed?src=o25bim5rvcu42mfnqilirpmp44@group.calendar.google.com).

If you've topics that you'd like to have included in the December meeting, please comment below. Any additional information and/or pre-reading that you could share with fellow attendees would be much appreciated.

Ongoing meeting topics are as follows:
- preparation for the [Q1 Face-to-Face](https://github.com/WICG/webcomponents/issues/1031) with implementors
  - these are the [topics from TPAC](https://github.com/WICG/webcomponents/issues/1026) that we're looking to follow up on
  - ways that the CG can be more active in "landing" specs/APIs
- review of issues/PRs/etc submitted to the [Community Protocols](https://github.com/webcomponents-cg/community-protocols) project
- longer future spec discussions for Face-to-face meetings with implementors later in 2024

While you're waiting, join the conversation on [Discord](https://discord.gg/uBcU8Q7pnv)!

**Comment by o-t-w** [comment]
I would like to add HTML modules to the agenda. 

Back in 2019 there was excitement about the [intent to implement](https://x.com/kennethrohde/status/1085774534324690945?s=20) by the Edge team. Because of all the spec changes with what were then called import assertions, this got stalled. The last remaining issue with the import attributes spec was [closed recently](https://github.com/whatwg/html/issues/7233). Import attributes are supported in Safari beta. 

It feels like HTML modules have been forgotten about in everyone's agenda. I wonder if there is more that can be done to try to recreate some momentum for this?

**Comment by matthewp** [comment]
I would like to add two things:

* Clarification on the current barrier to a merged proposal. I am explicitly *not* wanting to debate what the barrier should be, but to clarify what it currently is. The outcome of this discussion would be an update to the readme.
* This proposal template: https://github.com/webcomponents-cg/community-protocols/pull/47

**Comment by nolanlawson** [comment]
Just to clarify: it's at December 7th, 11am ET/8am PT/5pm CET

I would actually like to discuss `defer-hydration` (https://github.com/webcomponents-cg/community-protocols/pull/15). My goal is to understand 1) what an interoperable implementation would look like, and 2) if any other WC frameworks are considering implementing it or have implemented it (other than Lit).

**Comment by Westbrook** [comment]
@o-t-w in preparation for discussing this next month and at Face-to-Faces into the new year, would you be able to submit a PR to https://github.com/WICG/webcomponents/blob/gh-pages/proposals/html-modules-explainer.md that supported the more current Import Attributes syntax? I know normalizing that to the latest APIs will be a useful part of the conversations there.

**Comment by o-t-w** [comment]
@Westbrook [PR here](https://github.com/WICG/webcomponents/pull/1039) I've updated the syntax and updated one of the issue links.

**Comment by anlexN** [comment]
today, web component have 4 lifecycle by itself:

- `connectedCallback()`
- `disconnectedCallback()`
- `adoptedCallback()`
- `attributeChangedCallback()`

but [stenciljs](https://stenciljs.com/) and [lit](https://lit.dev/) add more lifecycle.

from the view of standard, are they resonable? or will standard add more lifecycle in the future too?
