### ISSUE TITLE
May Meeting Agenda and Scheduling

### ISSUE THREAD

**Issue by Westbrook** [w3c/webcomponents-cg#94]
For those of you who would like to take part in the May meeting of the Web Components Community Group, please share your availability [here](https://www.when2meet.com/?24886702-2GtG9) as we work to schedule the right day/time to gather. Don't forget, all WCCG events are listed on [this calendar](https://calendar.google.com/calendar/u/0/embed?src=o25bim5rvcu42mfnqilirpmp44@group.calendar.google.com). 📆

After a great face-to-face with implementors on May 3rd, there is lots of [work for the community group to follow up on](https://github.com/WICG/webcomponents/issues/1050#issuecomment-2093610922). Let's dive into the action items, and see what sort of breakout and discussions we want to drive through the summer months in advance of a July face-to-face with implementors!

As a reminder, we chat between meetings in Discord, where [we'd love to hear from you](https://discord.gg/yMgm8XGs).

If there are other topics you'd like to discuss, breakouts you would already like to have scheduled, or anything else, please drop your thoughts in the comments below!

**Comment by filimon-danopoulos** [comment]
I would like an update on the current state of the DOM Parts proposal if possible.

**Comment by michaelwarren1106** [comment]
Agenda Item: **Discuss how we're going to narrow down use cases for Open Stylable.**

It was suggested at the Face to Face that we need to narrow down use cases because in listing them there seem to be a lot of general use cases which makes finding solutions difficult.

Given that one of the reasons there are so many use cases is because we havent necessarily all agreed on the approach/features that are needed, we should discuss a plan for how we're going to narrow down the use cases, or decide on taking a different approach, etc. Either way, we should get to a point where we can agree on the ask for implementers surrounding open styleable WCs

**Comment by Westbrook** [comment]
> I would like an update on the current state of the DOM Parts proposal if possible.

I've not been following this too closely. Maybe @justinfagnani or @EisenbergEffect have any progress or action items they could report back to the CG on this?

**Comment by justinfagnani** [comment]
> > I would like an update on the current state of the DOM Parts proposal if possible.
> 
> I've not been following this too closely. Maybe @justinfagnani or @EisenbergEffect have any progress or action items they could report back to the CG on this?

Not much to report. Chrome is trying to improve overall bindings performance, which could make their DOM Parts prototype perf-positive. Other than that, no movement that I know of.

**Comment by justinfagnani** [comment]
I'd like to see an open-ended discussion on contribution opportunities within the WCCG ecosystem.

**Comment by Westbrook** [comment]
> Not much to report. Chrome is trying to improve overall bindings performance, which could make their DOM Parts prototype perf-positive. Other than that, no movement that I know of.

Did any of these tests make it behind a flag or something in Canary so that non-Chrome people can work with the APIs?

**Comment by Westbrook** [comment]
> I'd like to see an open-ended discussion on contribution opportunities within the WCCG ecosystem.

Will you be with us tomorrow to share more about what you mean by "contribution opportunities"? Sounds like a productive discussion!

**Comment by justinfagnani** [comment]
> > I'd like to see an open-ended discussion on contribution opportunities within the WCCG ecosystem.
> 
> Will you be with us tomorrow to share more about what you mean by "contribution opportunities"? Sounds like a productive discussion!

I'll be there, but I can share now: I mean how the WCCG can self-serve and contribute to the projects that we rely on, especially polyfills, tools, platform tests, specs, etc.

Will you be there @keithamus?

**Comment by keithamus** [comment]
I will do my best to make it!

**Comment by Westbrook** [comment]
Thanks everyone for joining! Meeting notes are [available here](https://docs.google.com/document/d/1jOz2Mu8y49j81WPE7__sHkyoUQey6X09JNiYmEh4b1I/edit#heading=h.5wa5qluob2zb). 🙇🏼 

**Action Items:**
- [ ] Focus out efforts on Cross Root ARIA and Scoped Custom Element Registries
- [ ] Write WPTs for [Reference Target](https://github.com/WICG/aom/blob/gh-pages/reference-target-explainer.md)
- [ ] Schedule a kick-off for the TPAC report
- [ ] Schedule a kick-off for the next phase of Style API discussions

See you next time 🖖🏼 

<details>
    <summary>Meeting chat inside...</summary>

You
11:01 AM
https://docs.google.com/document/d/1jOz2Mu8y49j81WPE7__sHkyoUQey6X09JNiYmEh4b1I/edit#heading=h.5wa5qluob2zb
keep
Pinned
Michael Warren
11:02 AM
we're not closed off like some of those OTHER community groups....lul
Jesse Jurman
11:02 AM
I will definitely miss things, so please add things you can :D
Owen Buckley
11:06 AM
https://github.com/WICG/webcomponents/issues/1050#issuecomment-2093610922
Keith Cirkel
11:07 AM
@Michael Warren would you kindly mute please - there's a little background noise coming from your mic I think
Michael Warren
11:14 AM
sorry my b
Pascal Vos
11:15 AM
same goes for accessibility web should be usable for everyone so you cant leave shadowroot  out the equation
Zachary Handley
11:15 AM
Do you guys feel like without keeping ahead of react / spa’s the names / conventions get pushed toward the popular features?
Michael Warren
11:15 AM
not quite sure what you mean zach?
Nolan Lawson
11:16 AM
fwiw Reference Target proposal is generic enough to handle popover/invoker/etc (any idref) https://github.com/WICG/aom/blob/gh-pages/reference-target-explainer.md
Michael Warren
11:17 AM
sorry, didnt mean to de-rail the agenda so bad haha
Pascal Vos
11:18 AM
is this not something that the implementors would ask as well ?
Zachary Handley
11:18 AM
I guess I feel like even though the DOM and things like NextJs are separate, there’s no good definition of SSR, SPA, SSG, that strictly defines how they work and operate. So for instance for testing, how does one know how to test a component working in multiple frameworks? I feel like web standards should define how these things should work, personally
Nolan Lawson
11:19 AM
zachary: have you seen https://custom-elements-everywhere.com/ ?
Michael Warren
11:20 AM
thats a tough one imo...web standards dont govern userland frameworks...we can always influence, but if frameworks exist that dont adopt the standards for whatever reasons, thats between that framework and their users
Zachary Handley
11:21 AM
Interesting
I guess I feel like, having some definition of what SSR is for instance e.g. having a render function or I’m not sure
Zachary Handley
11:22 AM
I’m still learning, I just know react makes up so much it’s frustrating
Owen Buckley
11:22 AM
there is some attempt at that, at least within WCs, in the form of community protocols 
https://github.com/webcomponents-cg/community-protocols
Zachary Handley
11:23 AM
Ooh amazing, thank you guys for the links!
Dave Rupert
11:23 AM
+1 the conversation around openstyleable got a bit hijacked by specific implementations as opposed to core needs.
Zachary Handley
11:24 AM
Would you guys recommend lit WC or creating my own cross framework components? Sorry if that’s super unrelated
Keith Cirkel
11:24 AM
To attend a csswg meeting you need to be an employee of a w3 member company (members list for w3 is here, so look for your company name in this list: https://www.w3.org/membership/list/)

If your company is a member you will need to sign up for a w3 account: https://www.w3.org/account/request/.

Additionally you'll need to reach out to your company rep (an employee at your company). You'll need to find out who that is, and reach out to them, and they can help you attend the meetings.
Michael Warren
11:24 AM
yeah those use cases threads were a mess haha
zach, Lit is great :)
web components themselves are already cross-frameworks, but the integration code needed is up to the frameworks, not libs like Lit etc
Nolan Lawson
11:25 AM
Benny: take a look at reference target :) https://github.com/WICG/aom/blob/gh-pages/reference-target-explainer.md
Benny Powers
11:25 AM
ty
Nolan Lawson
11:25 AM
Also ARIA element reflection is Intent-to-Implement in Chrome and Intent-to-Prototype in Firefox
Michael Warren
11:26 AM
🔥
Nolan Lawson
11:26 AM
https://nolanlawson.com/2022/11/28/shadow-dom-and-accessibility-the-trouble-with-aria/#:~:text=not%20ready%20yet.-,2024%20update,-%3A%20implementations%20have
Benny Powers
11:28 AM
correct
Pascal Vos
11:29 AM
💯steve
Benny Powers
11:29 AM
x-root aria is (correct me if im' wrong) why salesforce is still polyfilling sd
Nolan Lawson
11:29 AM
we're working on a cross-root ARIA polyfill but it's nasty. so agree
benny: that and styling yeah
Michael Warren
11:30 AM
keith and luke (and im sure there's many others) are our heroes :)
James Stuckey Weber
11:31 AM
Web Platform Tests are also very helpful for Polyfill development
Sasha Firsov
11:31 AM
link to Web Engines hack list.plz?
You
11:31 AM
Learn about WPT writing, here: https://www.youtube.com/watch?v=lPZtWDWHuZg
Brian Kardell
11:31 AM
sasha you mean https://webengineshackfest.org/ ?
Sasha Firsov
11:32 AM
thanks!
Zachary Handley
11:34 AM
Oh
Is safari ever gonna catch up?
like, just in general
You
11:34 AM
https://github.com/WICG/webcomponents/issues/1047
Zachary Handley
11:34 AM
https://ios404.com
Benny Powers
11:34 AM
if there's time later, i have a question about scoped ce registries / import map scopes (and if they can interact)
Benny Powers
11:36 AM
@Keith Cirkel i'd be interested in pairing/shadowing on WPT
Zachary Handley
11:36 AM
I’d love to be in vc with you guys occasionally just to learn more tbh
Benny Powers
11:36 AM
GMT-2 Jerusalem time
(make that +2)
Michael Warren
11:38 AM
+1 one meeting for "working", one for status updating?
i know thats a lot of meetings perhaps
Keith Cirkel
11:39 AM
https://k9l.io/book <--- book a pairing hour with here
s/with/with me
Dave Rupert
11:41 AM
AS A Web Component Enthusiast
I WANT ...
Owen Buckley
11:41 AM
TPAC report "promotoed" items?
Michael Warren
11:46 AM
thats kinda what i was envisioning...in product owner land, there'd be a "feature" called" "cross root aria" and under that feature might be several "tasks" like "write WPT tests", "answer open questions" etc...so that the folks that are driving cross-root aria would know what to focus on etc
Brian Kardell
11:51 AM
He said he doesn't now
:)
Brian Kardell
11:52 AM
It's a shame it is all on the issue that happened to grab that name first
Michael Warren
11:53 AM
+1 to that, theming is the kinds of styles you might write, not whether or not those styles actually apply to something heh
Michael Warren
11:55 AM
open stylable is important to me in a general "more adoption of WC/shadow roots" kinda way, not because I'd necessarily use it immediately upon release haha
Michael Warren
11:58 AM
imo there's definitely "categories" of things that WCs need...marketing (webcomponents.org etc), tooling (open-wc/modern web/Lit), specs and W3c stuff etc...
i wonder if we should like "appoint" leaders of those categories that volunteer to help manage (as best they can) those categories?
Luke Dary
11:59 AM
Event orchestration isn't something we think about much.
Nathan Knowler
11:59 AM
I’m working on one about progressive enhancement and the shadow dom

</details>
